// packages/fhevm-next-demo/src/components/Counter.tsx
"use client";

import React, { useEffect, useMemo, useState } from "react";
import { ethers } from "ethers";
import { useFhevm } from "@fhevm/react";
import { abis } from "@fhevm/shared";

const FHECounter = abis.deployedContracts["11155111"]["FHECounter"];

export function Counter() {
  const { sdk, signer, address, loading } = useFhevm();
  const [counter, setCounter] = useState<number | null>(null);
  const [busy, setBusy] = useState(false);

  const contract = useMemo(() => {
    if (!signer) return null;
    return new ethers.Contract(FHECounter.address, FHECounter.abi, signer);
  }, [signer]);

  const getCounter = async () => {
    if (!sdk || !contract || !address) return;
    setBusy(true);
    try {
      const encryptedValue = await contract.getCount();
      const pk = await sdk.getPublicKey();
      const sig = await sdk.createEIP712(pk);
      const decrypted = await sdk.decrypt([encryptedValue], address, sig);
      setCounter(Number(decrypted.plaintext));
    } catch (err) {
      console.error("Failed to get counter:", err);
    } finally {
      setBusy(false);
    }
  };

  const increment = async () => {
    if (!sdk || !contract || !address) return;
    setBusy(true);
    try {
      const { handles, inputProof } = await sdk.encryptInputs(address, [
        { type: "u32", value: 1 },
      ]);
      const tx = await contract.increment(handles[0], inputProof);
      await tx.wait();
      await getCounter();
    } catch (err) {
      console.error("Increment failed:", err);
    } finally {
      setBusy(false);
    }
  };

  const decrement = async () => {
    if (!sdk || !contract || !address) return;
    setBusy(true);
    try {
      const { handles, inputProof } = await sdk.encryptInputs(address, [
        { type: "u32", value: 1 },
      ]);
      const tx = await contract.decrement(handles[0], inputProof);
      await tx.wait();
      await getCounter();
    } catch (err) {
      console.error("Decrement failed:", err);
    } finally {
      setBusy(false);
    }
  };

  // ✅ Only run once when ready
  useEffect(() => {
    if (!loading && sdk && contract && address) {
      getCounter();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loading, sdk, contract, address]);

  if (loading) return <p>🕓 Connecting wallet...</p>;

  return (
    <div style={{ textAlign: "center", marginTop: "4rem" }}>
      <h2>🔐 Encrypted Counter</h2>
      <p>Connected: {address}</p>
      <h3>{counter === null ? "…" : counter}</h3>
      <div style={{ display: "flex", justifyContent: "center", gap: "1rem" }}>
        <button onClick={decrement} disabled={busy}>
          ➖ Decrement
        </button>
        <button onClick={increment} disabled={busy}>
          ➕ Increment
        </button>
      </div>
      <div style={{ marginTop: "1rem" }}>
        <button onClick={getCounter} disabled={busy}>
          🔄 Refresh
        </button>
      </div>
      {busy && <p>⏳ Please wait…</p>}
    </div>
  );
}

// packages/fhevm-vue-demo/src/components/Counter.vue
<template>
  <div>
    <p v-if="loading">🕓 Connecting wallet...</p>

    <div v-else>
      <p>Connected: {{ address }}</p>
      <h2>{{ counter ?? "…" }}</h2>

      <div class="buttons">
        <button @click="decrement" :disabled="busy">➖ Decrement</button>
        <button @click="increment" :disabled="busy">➕ Increment</button>
      </div>

      <div class="buttons">
        <button @click="getCounter" :disabled="busy">🔄 Refresh</button>
      </div>

      <p v-if="busy">⏳ Please wait…</p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, watchEffect } from "vue";
import { ethers } from "ethers";
import { useFhevm, useEncrypt } from "@fhevm/vue";
import { abis } from "@fhevm/shared";

const { sdk, signer, address, loading } = useFhevm();
const { encrypt } = useEncrypt();

const counter = ref<number | null>(null);
const busy = ref(false);

// Example FHE Counter ABI
const FHECounter = abis.deployedContracts["11155111"]["FHECounter"];
let contract: ethers.Contract | null = null;

watchEffect(() => {
  if (signer.value) {
    contract = new ethers.Contract(FHECounter.address, FHECounter.abi, signer.value);
  }
});

async function getCounter() {
  if (!sdk.value || !contract || !address.value) return;
  busy.value = true;

  try {
    const encrypted = await contract.getCount();
    const pk = await sdk.value.getPublicKey();
    const sig = await sdk.value.createEIP712(pk);
    const decrypted = await sdk.value.decrypt([encrypted], address.value, sig);
    counter.value = Number(decrypted.plaintext);
  } catch (err) {
    console.error("getCounter failed", err);
  } finally {
    busy.value = false;
  }
}

async function increment() {
  if (!sdk.value || !contract || !address.value) return;
  busy.value = true;

  try {
    const { handles, inputProof } = await encrypt([{ type: "u32", value: 1 }]);
    const tx = await contract.increment(handles[0], inputProof);
    await tx.wait();
    await getCounter();
  } catch (err) {
    console.error("increment failed", err);
  } finally {
    busy.value = false;
  }
}

async function decrement() {
  if (!sdk.value || !contract || !address.value) return;
  busy.value = true;

  try {
    const { handles, inputProof } = await encrypt([{ type: "u32", value: 1 }]);
    const tx = await contract.decrement(handles[0], inputProof);
    await tx.wait();
    await getCounter();
  } catch (err) {
    console.error("decrement failed", err);
  } finally {
    busy.value = false;
  }
}
</script>

<style scoped>
.buttons {
  display: flex;
  justify-content: center;
  gap: 1rem;
  margin: 1rem 0;
}
</style>
